version: '3.8'

services:
  frontend:
    build:
      context: ./demofe
      dockerfile: Dockerfile
    volumes:
      - ./demofe:/app          # đúng theo context FE
      - /app/node_modules
    ports:
      - "3000:3000"
    env_file:
      - ./demofe/.env          # dùng file .env thay vì environment thủ công
    command: npm start

  backend:
    restart: always
    build:
      context: ./cancer_detection_api
      dockerfile: Dockerfile
    volumes:
      - ./cancer_detection_api:/app   # đúng context BE
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - ./cancer_detection_api/.env   # dùng .env thay vì hardcode
    # nếu vẫn muốn override thêm:
    

  db:
    image: postgres:17
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=phamkien12345
      - POSTGRES_DB=cancer_detection
    ports:
      - "5432:5432"

volumes:
  postgres_data:
